repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.13.0
  hooks:
    - id: ruff-check
      args: [ --fix, --exit-non-zero-on-fix ]
    - id: ruff-format
      args: [ --exit-non-zero-on-format ]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.18.1
  hooks:
  - id: mypy
